# Generated by Django 2.2.2 on 2019-06-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, max_length=30, verbose_name='Descricao Da Marca')),
                ('ativo', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'marcas',
                'ordering': ('descricao',),
            },
        ),
    ]
