# Generated by Django 2.2.2 on 2019-06-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estrutura', models.CharField(max_length=50, unique=True, verbose_name='chave estruturada')),
                ('descricao', models.TextField(blank=True, max_length=100, verbose_name='Descricao do plano')),
                ('ativo', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ('estrutura',),
            },
        ),
    ]
