# Generated by Django 2.2.2 on 2019-06-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20190617_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
